### ISSUE TITLE
Live Dashboard to track sticker requests

### ISSUE THREAD

**Issue by deven96** [deven96/whatsticker#20]
A public dashboard where everyone can view metrics on stickerization. Some metrics to track
- Country code
- Media type
- Media size 
- Validated 
- Group chat
- Time of request

**Comment by derhnyel** [comment]
Yeah. I was looking at using a redis plugin for grafana.. I could stream the data in real time

**Comment by derhnyel** [comment]
https://redisgrafana.github.io/redis-datasource/streaming/

@MeNsaaH  what do you think about this?

**Comment by MeNsaaH** [comment]
that is a redis plugin for grafana. It's for displaying redis-related metrics on grafana. The steps here should be:

1. Create a `/metrics` endpoint within the application that exports the metrics we want to use to create our dashboards.
2. Deploy Grafana and Prometheus within another VM, and have prometheus scrape metrics from that endpoint
3. Create dashboard for the application on grafana.

**Comment by deven96** [comment]
Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that?  @MeNsaaH 
Instead of an endpoint can't we push it into a queue that Prometheus would read from?

**Comment by deven96** [comment]
There's also https://prometheus.io/docs/prometheus/latest/querying/api/#remote-write-receiver

**Comment by deven96** [comment]
https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/push

**Comment by MeNsaaH** [comment]
> Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that? @MeNsaaH Instead of an endpoint can't we push it into a queue that Prometheus would read from?

Does the application have a public endpoint that can accessed? If yes, I don't think you need to worry about the storing the metrics. You also don't need to store it in a DB. prometheus metrics are instantaneous. That means when prometheus hits the endpoint, it's records are wiped. Hitting the endpoint shows new metrics not old metrics.

Prometheus is the one that is deployed with a DB, hence no need for persistence on the application layer.

**Comment by MeNsaaH** [comment]
> Yeah i get. This is what i understand from your explanation correct me if i am wrong:
> 
> 1. Prometheus would basically be monitoring and alerting if a message is sent. It would then collect and store the metrics from the endpoint created and grafana consumes this in realtime.
> 
> My question is what kind of endpoint am i creating ??

You'll create a simple rest endpoint that returns metrics. Look at the examples here https://github.com/prometheus/client_golang to see how this is done

**Comment by deven96** [comment]
> > Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that? @MeNsaaH Instead of an endpoint can't we push it into a queue that Prometheus would read from?
> 
> Does the application have a public endpoint that can accessed? If yes, I don't think you need to worry about the storing the metrics. You also don't need to store it in a DB. prometheus metrics are instantaneous. That means when prometheus hits the endpoint, it's records are wiped. Hitting the endpoint shows new metrics not old metrics.
> 
> Prometheus is the one that is deployed with a DB, hence no need for persistence on the application layer.

The application does not have public endpoints at all. Except we create a third queue where we put the metrics on in form of a struct then the endpoint would fetch off that queue @derhnyel

**Comment by MeNsaaH** [comment]
> > > Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that? @MeNsaaH Instead of an endpoint can't we push it into a queue that Prometheus would read from?
> > 
> > 
> > Does the application have a public endpoint that can accessed? If yes, I don't think you need to worry about the storing the metrics. You also don't need to store it in a DB. prometheus metrics are instantaneous. That means when prometheus hits the endpoint, it's records are wiped. Hitting the endpoint shows new metrics not old metrics.
> > Prometheus is the one that is deployed with a DB, hence no need for persistence on the application layer.
> 
> The application does not have public endpoints at all. Except we create a third queue where we put the metrics on in form of a struct then the endpoint would fetch off that queue @derhnyel

Eweeey. If the app has no http endpoint, then the pushgateway might be a way to go here.

**Comment by derhnyel** [comment]
> > > Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that? @MeNsaaH Instead of an endpoint can't we push it into a queue that Prometheus would read from?
> > 
> > 
> > Does the application have a public endpoint that can accessed? If yes, I don't think you need to worry about the storing the metrics. You also don't need to store it in a DB. prometheus metrics are instantaneous. That means when prometheus hits the endpoint, it's records are wiped. Hitting the endpoint shows new metrics not old metrics.
> > Prometheus is the one that is deployed with a DB, hence no need for persistence on the application layer.
> 
> The application does not have public endpoints at all. Except we create a third queue where we put the metrics on in form of a struct then the endpoint would fetch off that queue @derhnyel

So the third queue would be fine but how does it compare with an endpoint. Which would be more efficient and manageable?

**Comment by MeNsaaH** [comment]
> > > > Creating a /metrics endpoint would mean having some database persistence wrapped by a web endpoint right?. Isn't there some sort of way not to do that? @MeNsaaH Instead of an endpoint can't we push it into a queue that Prometheus would read from?
> > > 
> > > 
> > > Does the application have a public endpoint that can accessed? If yes, I don't think you need to worry about the storing the metrics. You also don't need to store it in a DB. prometheus metrics are instantaneous. That means when prometheus hits the endpoint, it's records are wiped. Hitting the endpoint shows new metrics not old metrics.
> > > Prometheus is the one that is deployed with a DB, hence no need for persistence on the application layer.
> > 
> > 
> > The application does not have public endpoints at all. Except we create a third queue where we put the metrics on in form of a struct then the endpoint would fetch off that queue @derhnyel
> 
> So the third queue would be fine but how does it compare with an endpoint. Which would be more efficient and manageable? @deven96 @MeNsaaH

I'm not sure what your question here is @derhnyel

**Comment by deven96** [comment]
Maybe within the workers instead of master @MeNsaaH. But how would we retrieve the metrics

**Comment by derhnyel** [comment]
@deven96 What about the steps we highlighted earlier .. Adding those metrics from the master in the struct being put in the queue ?

**Comment by deven96** [comment]
Yeah what about them?... Put them in the struct, get them in the worker when the struct has been de serialized, push them to the prometheus push gateway

**Comment by deven96** [comment]
> we could use prometheus and grafana hosted in a different environment to retrieve the metrics from the http endpoint anytime a message is received and create the dashboard

@derhnyel  don't worry about the prometheus and grafana side... Let @MeNsaaH handle it. You focus on adding the pushgateway to the docker compose setup, exposing the port for the push gateway to the host ans pushing the metrics to the push gateway. We'd have Onuh create a firewall rule for the prod server that accepts traffic on that port. @MeNsaaH will then point the grafana dashboard to that port. 

Ensure you set up the pushgateway with a file for persistence (it's on the readme). So that it can survive restarts

**Comment by deven96** [comment]
@MeNsaaH We now have the metrics endpoint in code, when can we set up prometheus and grafana?

@Iamdavidonuh we would actually need you to open up the port `9091` on the prod instance so that prometheus can scrape for metrics there
