### ISSUE TITLE
Track sticker creator

### ISSUE THREAD

**Issue by deven96** [deven96/whatsticker#21]
In hindsight @MeNsaaH. I've received one or two emails about people seeing their pictures used disrespectfully in a sticker. Whatsticker in theory should be able to receive stickers in a DM and tell you the number that created it

This can be done if we append exif information containing the number to stickers and then extract it (if possible)  when a sticker is sent

**Comment by MeNsaaH** [comment]
We can't control what people do with stickers. But yes, adding the creator metadata is not a bad idea

**Comment by deven96** [comment]
And I'm not sure if we want to give everyone the power to be able to track creator of a sticker. We can embed it incase we ourselves have to track the creator, but nothing else

**Comment by deven96** [comment]
I opened this because I've had two requests from people looking to track creators of stickers who they felt were insulting use of their images. Not sure how much of that we can regulate. I also don't think we should

**Comment by deven96** [comment]
Closing this cuz we wouldn't be tracking creators
